from typing import List, Dict, Optional, Any

from src.common.dto.build import BuildResult
from src.common.dto.failure import FailureRecord
from src.common.config.constants import BuildStatus
from src.common.config.logging_config import get_logger


logger = get_logger(__name__)


class HTMLFormatter:
    STATUS_COLORS = {
        BuildStatus.SUCCESS: "#28a745",
        BuildStatus.FAILURE: "#dc3545",
        BuildStatus.RUNNING: "#ffc107",
        BuildStatus.PENDING: "#6c757d",
        BuildStatus.CANCELLED: "#6c757d",
    }

    def format_build_report(
        self,
        build: BuildResult,
        failures: Optional[List[FailureRecord]] = None,
        include_styles: bool = True,
    ) -> str:
        sections = []
        
        if include_styles:
            sections.append(self._get_styles())
        
        sections.append(self._format_header(build))
        sections.append(self._format_build_details(build))
        
        if failures:
            sections.append(self._format_failures(failures))
        
        sections.append(self._format_footer())
        
        return "\n".join(sections)

    def _get_styles(self) -> str:
        return """
<style>
.ci-report { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; }
.ci-header { padding: 20px; color: white; border-radius: 8px 8px 0 0; }
.ci-content { background: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; }
.ci-section { background: white; padding: 15px; margin: 10px 0; border-radius: 4px; border: 1px solid #dee2e6; }
.ci-section h3 { margin-top: 0; border-bottom: 1px solid #eee; padding-bottom: 8px; }
.ci-badge { display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
.ci-success { background: #d4edda; color: #155724; }
.ci-failed { background: #f8d7da; color: #721c24; }
.ci-warning { background: #fff3cd; color: #856404; }
.ci-failure-item { background: #fff5f5; border-left: 3px solid #dc3545; padding: 10px; margin: 8px 0; }
.ci-code { background: #f4f4f4; padding: 10px; font-family: monospace; font-size: 12px; overflow-x: auto; border-radius: 4px; }
.ci-table { width: 100%; border-collapse: collapse; }
.ci-table th, .ci-table td { padding: 8px; text-align: left; border-bottom: 1px solid #dee2e6; }
.ci-table th { background: #f8f9fa; }
.ci-footer { text-align: center; padding: 15px; font-size: 12px; color: #6c757d; }
</style>
"""

    def _format_header(self, build: BuildResult) -> str:
        color = self.STATUS_COLORS.get(build.status, "#6c757d")
        status_text = build.status.value.upper()
        
        return f"""
<div class="ci-report">
<div class="ci-header" style="background: {color};">
    <h2 style="margin: 0;">Build {status_text}</h2>
    <p style="margin: 5px 0 0 0; opacity: 0.9;">
        {build.request.repository} @ {build.request.branch}
    </p>
</div>
"""

    def _format_build_details(self, build: BuildResult) -> str:
        duration = self._format_duration(build.duration_seconds)
        
        return f"""
<div class="ci-content">
    <div class="ci-section">
        <h3>Build Details</h3>
        <table class="ci-table">
            <tr><th>Build ID</th><td>{str(build.build_id)[:8]}</td></tr>
            <tr><th>Commit</th><td><code>{build.request.commit_sha[:7] if build.request.commit_sha else 'N/A'}</code></td></tr>
            <tr><th>Duration</th><td>{duration}</td></tr>
            <tr><th>Status</th><td><span class="ci-badge ci-{build.status.value}">{build.status.value}</span></td></tr>
        </table>
    </div>
"""

    def _format_failures(self, failures: List[FailureRecord]) -> str:
        failure_items = ""
        for failure in failures[:10]:
            failure_items += f"""
    <div class="ci-failure-item">
        <strong>{failure.category.value}</strong>
        {f'<span style="color: #666;"> in {failure.component}</span>' if failure.component else ''}
        <div class="ci-code">{self._escape_html(str(failure.error_message)[:300]) if failure.error_message else 'No details'}</div>
        <small style="color: #666;">{failure.file_path or 'unknown'}:{failure.line_number or 0}</small>
    </div>
"""
        
        return f"""
    <div class="ci-section">
        <h3>❌ Failures ({len(failures)})</h3>
        {failure_items}
    </div>
"""

    def _format_footer(self) -> str:
        return """
</div>
<div class="ci-footer">
    Generated by ROCm CI/CD Pipeline v1.0.0
</div>
</div>
"""

    def _format_duration(self, seconds: Optional[float]) -> str:
        if not seconds:
            return "N/A"
        
        if seconds < 60:
            return f"{int(seconds)}s"
        elif seconds < 3600:
            return f"{int(seconds // 60)}m {int(seconds % 60)}s"
        else:
            hours = int(seconds // 3600)
            minutes = int((seconds % 3600) // 60)
            return f"{hours}h {minutes}m"

    def _escape_html(self, text: str) -> str:
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )

    def create_table(
        self,
        headers: List[str],
        rows: List[List[str]],
        table_class: str = "ci-table",
    ) -> str:
        header_cells = "".join(f"<th>{self._escape_html(h)}</th>" for h in headers)
        header_row = f"<tr>{header_cells}</tr>"
        
        data_rows = []
        for row in rows:
            cells = "".join(f"<td>{self._escape_html(str(c))}</td>" for c in row)
            data_rows.append(f"<tr>{cells}</tr>")
        
        return f"""
<table class="{table_class}">
    <thead>{header_row}</thead>
    <tbody>{"".join(data_rows)}</tbody>
</table>
"""

    def create_alert(self, message: str, alert_type: str = "info") -> str:
        colors = {
            "info": ("#cce5ff", "#004085"),
            "success": ("#d4edda", "#155724"),
            "warning": ("#fff3cd", "#856404"),
            "error": ("#f8d7da", "#721c24"),
        }
        bg, fg = colors.get(alert_type, colors["info"])
        
        return f"""
<div style="background: {bg}; color: {fg}; padding: 12px; border-radius: 4px; margin: 10px 0;">
    {self._escape_html(message)}
</div>
"""

    def create_badge(self, text: str, color: str = "#6c757d") -> str:
        return f'<span style="background: {color}; color: white; padding: 2px 8px; border-radius: 10px; font-size: 12px;">{self._escape_html(text)}</span>'
