from typing import Dict, List, Optional, Any
from datetime import datetime, timezone

from src.common.dto.build import BuildResult
from src.common.dto.failure import FailureRecord
from src.common.config.constants import BuildStatus
from src.common.config.logging_config import get_logger


logger = get_logger(__name__)


class EmailTemplate:
    HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ROCm CI/CD Build Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background: linear-gradient(135deg, {header_color} 0%, {header_color_dark} 100%);
            color: white;
            padding: 20px;
            border-radius: 8px 8px 0 0;
        }}
        .header h1 {{
            margin: 0 0 10px 0;
            font-size: 24px;
        }}
        .header .meta {{
            opacity: 0.9;
            font-size: 14px;
        }}
        .content {{
            background: #f9f9f9;
            padding: 20px;
            border: 1px solid #e0e0e0;
            border-top: none;
        }}
        .status-badge {{
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-weight: bold;
            font-size: 12px;
            text-transform: uppercase;
        }}
        .status-success {{ background: #28a745; color: white; }}
        .status-failed {{ background: #dc3545; color: white; }}
        .status-running {{ background: #ffc107; color: black; }}
        .status-pending {{ background: #6c757d; color: white; }}
        .section {{
            background: white;
            padding: 15px;
            margin: 15px 0;
            border-radius: 8px;
            border: 1px solid #e0e0e0;
        }}
        .section h2 {{
            margin-top: 0;
            font-size: 18px;
            color: #444;
            border-bottom: 2px solid #eee;
            padding-bottom: 8px;
        }}
        .failure-item {{
            background: #fff5f5;
            border-left: 4px solid #dc3545;
            padding: 10px;
            margin: 10px 0;
            border-radius: 0 4px 4px 0;
        }}
        .failure-item h3 {{
            margin: 0 0 8px 0;
            font-size: 14px;
            color: #dc3545;
        }}
        .failure-item pre {{
            background: #f4f4f4;
            padding: 10px;
            overflow-x: auto;
            font-size: 12px;
            border-radius: 4px;
        }}
        .recommendation {{
            background: #f0f9ff;
            border-left: 4px solid #0066cc;
            padding: 10px;
            margin: 10px 0;
            border-radius: 0 4px 4px 0;
        }}
        .footer {{
            text-align: center;
            padding: 15px;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #e0e0e0;
        }}
        .button {{
            display: inline-block;
            padding: 10px 20px;
            background: #0066cc;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            margin: 5px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
        }}
        th, td {{
            padding: 8px 12px;
            text-align: left;
            border-bottom: 1px solid #e0e0e0;
        }}
        th {{
            background: #f4f4f4;
            font-weight: 600;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{status_icon} Build {status_text}</h1>
        <div class="meta">
            <strong>Repository:</strong> {repository}<br>
            <strong>Branch:</strong> {branch} | <strong>Commit:</strong> {commit_sha}<br>
            <strong>Duration:</strong> {duration}
        </div>
    </div>
    <div class="content">
        {sections}
    </div>
    <div class="footer">
        <a href="{logs_url}" class="button">View Full Logs</a>
        <a href="{dashboard_url}" class="button">Open Dashboard</a>
        <p>Generated by ROCm CI/CD Pipeline v1.0.0</p>
    </div>
</body>
</html>"""

    STATUS_COLORS = {
        BuildStatus.SUCCESS: ("#28a745", "#1e7e34"),
        BuildStatus.FAILURE: ("#dc3545", "#c82333"),
        BuildStatus.RUNNING: ("#ffc107", "#e0a800"),
        BuildStatus.PENDING: ("#6c757d", "#545b62"),
        BuildStatus.CANCELLED: ("#6c757d", "#545b62"),
    }

    STATUS_ICONS = {
        BuildStatus.SUCCESS: "✅",
        BuildStatus.FAILURE: "❌",
        BuildStatus.RUNNING: "🔄",
        BuildStatus.PENDING: "⏳",
        BuildStatus.CANCELLED: "🚫",
    }

    def __init__(self, dashboard_url: str = "", docs_url: str = ""):
        self._dashboard_url = dashboard_url
        self._docs_url = docs_url

    def render(
        self,
        build_result: BuildResult,
        failures: Optional[List[FailureRecord]] = None,
        recommendations: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        sections = []
        
        sections.append(self._render_summary_section(build_result))
        
        if failures:
            sections.append(self._render_failures_section(failures))
        
        if recommendations:
            sections.append(self._render_recommendations_section(recommendations))
        
        colors = self.STATUS_COLORS.get(build_result.status, ("#6c757d", "#545b62"))
        
        return self.HTML_TEMPLATE.format(
            header_color=colors[0],
            header_color_dark=colors[1],
            status_icon=self.STATUS_ICONS.get(build_result.status, "❓"),
            status_text=build_result.status.value.title(),
            repository=build_result.request.repository,
            branch=build_result.request.branch,
            commit_sha=build_result.request.commit_sha[:7] if build_result.request.commit_sha else "unknown",
            duration=self._format_duration(build_result.duration_seconds),
            sections="\n".join(sections),
            logs_url=build_result.logs_url or "#",
            dashboard_url=self._dashboard_url or "#",
        )

    def _render_summary_section(self, build: BuildResult) -> str:
        return f"""
        <div class="section">
            <h2>📊 Build Summary</h2>
            <table>
                <tr><th>Build ID</th><td>{str(build.build_id)[:8]}</td></tr>
                <tr><th>Status</th><td><span class="status-badge status-{build.status.value}">{build.status.value}</span></td></tr>
                <tr><th>Started</th><td>{build.started_at.strftime('%Y-%m-%d %H:%M UTC') if build.started_at else 'N/A'}</td></tr>
                <tr><th>Completed</th><td>{build.completed_at.strftime('%Y-%m-%d %H:%M UTC') if build.completed_at else 'In Progress'}</td></tr>
            </table>
        </div>
        """

    def _render_failures_section(self, failures: List[FailureRecord]) -> str:
        failure_items = ""
        for failure in failures[:5]:
            failure_items += f"""
            <div class="failure-item">
                <h3>{failure.category.value}: {failure.component or 'Unknown Component'}</h3>
                <pre>{str(failure.error_message)[:300] if failure.error_message else 'No error message'}</pre>
                <p><strong>Location:</strong> {failure.file_path or 'unknown'}:{failure.line_number or 0}</p>
            </div>
            """
        
        return f"""
        <div class="section">
            <h2>❌ Failures ({len(failures)})</h2>
            {failure_items}
        </div>
        """

    def _render_recommendations_section(self, recommendations: List[Dict[str, Any]]) -> str:
        rec_items = ""
        for i, rec in enumerate(recommendations[:3], 1):
            rec_items += f"""
            <div class="recommendation">
                <strong>{i}. {rec.get('title', 'Recommendation')}</strong>
                <p>{rec.get('description', '')}</p>
            </div>
            """
        
        return f"""
        <div class="section">
            <h2>💡 Recommended Actions</h2>
            {rec_items}
        </div>
        """

    def _format_duration(self, seconds: Optional[float]) -> str:
        if not seconds:
            return "N/A"
        
        if seconds < 60:
            return f"{int(seconds)}s"
        elif seconds < 3600:
            return f"{int(seconds // 60)}m {int(seconds % 60)}s"
        else:
            hours = int(seconds // 3600)
            minutes = int((seconds % 3600) // 60)
            return f"{hours}h {minutes}m"

    def render_plain_text(self, build_result: BuildResult) -> str:
        lines = [
            f"ROCm CI/CD Build Report",
            f"=" * 40,
            f"Status: {build_result.status.value}",
            f"Repository: {build_result.request.repository}",
            f"Branch: {build_result.request.branch}",
            f"Commit: {build_result.request.commit_sha}",
            f"Duration: {self._format_duration(build_result.duration_seconds)}",
            f"",
            f"View logs: {build_result.logs_url or 'N/A'}",
        ]
        return "\n".join(lines)
