from typing import Dict, List, Optional, Any
from datetime import datetime, timezone

from src.common.dto.build import BuildResult
from src.common.dto.failure import FailureRecord
from src.common.dto.fix import FixRecommendation
from src.common.config.constants import BuildStatus
from src.common.config.logging_config import get_logger


logger = get_logger(__name__)


class PRCommentTemplate:
    HEADER_TEMPLATE = """## {status_emoji} ROCm CI/CD Build Report

**Build ID:** `{build_id}`
**Branch:** `{branch}` | **Commit:** `{commit_sha}`
**Duration:** {duration} | **Completed:** {completed_at}

---
"""

    STATUS_TABLE_HEADER = """### Build Matrix Results

| ROCm Version | GPU Architecture | Build Type | Status | Duration |
|--------------|------------------|------------|--------|----------|
"""

    FAILURE_SECTION = """### ❌ Failures ({failure_count})

<details>
<summary>Click to expand failure details</summary>

{failure_details}
</details>

---
"""

    FAILURE_ITEM = """#### {category}: {component}

```
{error_excerpt}
```

**File:** `{file_path}:{line_number}`
**Signature:** `{signature}`

"""

    RECOMMENDATIONS_SECTION = """### 💡 Recommended Actions

{recommendations}

---
"""

    RECOMMENDATION_ITEM = """{index}. **{title}** (Confidence: {confidence}%)
   - {description}
   - Steps: {steps}
   - Estimated time: {time_estimate}

"""

    FOOTER_TEMPLATE = """---
<sub>
🔗 [Full Logs]({logs_url}) | [Build Dashboard]({dashboard_url}) | [Documentation]({docs_url})
<br>
Generated by ROCm CI/CD Pipeline v1.0.0
</sub>
"""

    STATUS_EMOJIS = {
        BuildStatus.SUCCESS: "✅",
        BuildStatus.FAILURE: "❌",
        BuildStatus.RUNNING: "🔄",
        BuildStatus.PENDING: "⏳",
        BuildStatus.CANCELLED: "🚫",
    }

    def __init__(self, dashboard_url: str = "", docs_url: str = ""):
        self._dashboard_url = dashboard_url
        self._docs_url = docs_url

    def render(
        self,
        build_result: BuildResult,
        failures: Optional[List[FailureRecord]] = None,
        recommendations: Optional[List[FixRecommendation]] = None,
        matrix_results: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        sections = []
        
        sections.append(self._render_header(build_result))
        
        if matrix_results:
            sections.append(self._render_matrix_table(matrix_results))
        
        if failures:
            sections.append(self._render_failures(failures))
        
        if recommendations:
            sections.append(self._render_recommendations(recommendations))
        
        sections.append(self._render_footer(build_result))
        
        return "\n".join(sections)

    def _render_header(self, build: BuildResult) -> str:
        status_emoji = self.STATUS_EMOJIS.get(build.status, "❓")
        duration = self._format_duration(build.duration_seconds)
        completed = build.completed_at.strftime("%Y-%m-%d %H:%M UTC") if build.completed_at else "In Progress"
        
        return self.HEADER_TEMPLATE.format(
            status_emoji=status_emoji,
            build_id=str(build.build_id)[:8],
            branch=build.request.branch,
            commit_sha=build.request.commit_sha[:7] if build.request.commit_sha else "unknown",
            duration=duration,
            completed_at=completed,
        )

    def _render_matrix_table(self, results: List[Dict[str, Any]]) -> str:
        table = self.STATUS_TABLE_HEADER
        
        for result in results:
            status_emoji = "✅" if result.get("success") else "❌"
            table += f"| {result.get('rocm_version', 'N/A')} | {result.get('gpu_arch', 'N/A')} | {result.get('build_type', 'release')} | {status_emoji} | {result.get('duration', 'N/A')} |\n"
        
        table += "\n---\n"
        return table

    def _render_failures(self, failures: List[FailureRecord]) -> str:
        failure_details = ""
        
        for failure in failures[:10]:
            failure_details += self.FAILURE_ITEM.format(
                category=failure.category.value,
                component=failure.component or "unknown",
                error_excerpt=str(failure.error_message)[:500] if failure.error_message else "No error message",
                file_path=failure.file_path or "unknown",
                line_number=failure.line_number or 0,
                signature=failure.signature[:16] if failure.signature else "none",
            )
        
        return self.FAILURE_SECTION.format(
            failure_count=len(failures),
            failure_details=failure_details,
        )

    def _render_recommendations(self, recommendations: List[FixRecommendation]) -> str:
        recs_text = ""
        
        for i, rec in enumerate(recommendations[:5], 1):
            steps_text = " → ".join(rec.steps[:3]) if rec.steps else "See documentation"
            recs_text += self.RECOMMENDATION_ITEM.format(
                index=i,
                title=rec.title,
                confidence=int(rec.confidence * 100),
                description=rec.description,
                steps=steps_text,
                time_estimate=f"{rec.estimated_time_minutes} min",
            )
        
        return self.RECOMMENDATIONS_SECTION.format(recommendations=recs_text)

    def _render_footer(self, build: BuildResult) -> str:
        return self.FOOTER_TEMPLATE.format(
            logs_url=build.logs_url or "#",
            dashboard_url=self._dashboard_url or "#",
            docs_url=self._docs_url or "#",
        )

    def _format_duration(self, seconds: Optional[float]) -> str:
        if not seconds:
            return "N/A"
        
        if seconds < 60:
            return f"{int(seconds)}s"
        elif seconds < 3600:
            return f"{int(seconds // 60)}m {int(seconds % 60)}s"
        else:
            hours = int(seconds // 3600)
            minutes = int((seconds % 3600) // 60)
            return f"{hours}h {minutes}m"

    def generate_summary(self, build: BuildResult) -> str:
        status_emoji = self.STATUS_EMOJIS.get(build.status, "❓")
        return f"{status_emoji} Build {build.status.value}: {build.request.repository}@{build.request.branch}"
